import http from './http'
export const getEntityTypes = () => http.get('/api/kg/entity-types')
export const createEntityType = (data) => http.post('/api/kg/entity-types', data)
export const updateEntityType = (id, data) => http.put(`/api/kg/entity-types/${id}`, data)
export const deleteEntityType = (id) => http.delete(`/api/kg/entity-types/${id}`)
export const getRelationTypes = () => http.get('/api/kg/relation-types')
export const createRelationType = (data) => http.post('/api/kg/relation-types', data)
export const updateRelationType = (id, data) => http.put(`/api/kg/relation-types/${id}`, data)
export const deleteRelationType = (id) => http.delete(`/api/kg/relation-types/${id}`)
export const getEntities = (params) => http.get('/api/kg/entities', { params })
export const getTriples = (params) => http.get('/api/kg/triples', { params })
export const getGraph = (params) => http.get('/api/kg/graph', { params })
export const execCypher = (data) => http.post('/api/kg/cypher', data)
export const qa = (data) => http.post('/api/kg/qa', data)
export const reasoning = (data) => http.post('/api/kg/reasoning', data)
export const getConflicts = (params) => http.get('/api/kg/conflicts', { params })
export const updateConflictStatus = (id, status) => http.put(`/api/kg/conflicts/${id}/status`, null, { params: { status } })
export const getCompletions = (params) => http.get('/api/kg/completions', { params })
export const applyCompletion = (id) => http.post(`/api/kg/completions/${id}/apply`)
export const getVersions = (params) => http.get('/api/kg/versions', { params })
export const createVersion = (data) => http.post('/api/kg/versions', data)
