import http from './http'
export const getUsers = (params) => http.get('/api/system/users', { params })
export const createUser = (data) => http.post('/api/system/users', data)
export const updateUser = (id, data) => http.put(`/api/system/users/${id}`, data)
export const deleteUser = (id) => http.delete(`/api/system/users/${id}`)
export const getRoles = () => http.get('/api/system/roles')
export const createRole = (data) => http.post('/api/system/roles', data)
export const updateRole = (id, data) => http.put(`/api/system/roles/${id}`, data)
export const deleteRole = (id) => http.delete(`/api/system/roles/${id}`)
export const getMenus = () => http.get('/api/system/menus')
export const createMenu = (data) => http.post('/api/system/menus', data)
export const updateMenu = (id, data) => http.put(`/api/system/menus/${id}`, data)
export const deleteMenu = (id) => http.delete(`/api/system/menus/${id}`)
export const getLogs = (params) => http.get('/api/system/logs', { params })
export const getDicts = (code) => http.get(`/api/system/dicts/${code}`)
